name: Integration tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PRISMA_ENDPOINT: ${{secrets.PRISMA_ENDPOINT}}
      PRISMA_SECRET: ${{secrets.PRISMA_SECRET}}
    steps:
      - name: Clone Frontend Repository
        uses: actions/checkout@v2
      - name: Clone Backend Repository
        uses: actions/checkout@v2
        with:
          repository: vladnicula/invoice-rest-api
          path: invoice-rest-api
          # ref: main
      - name: "Install Node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: "Install frontend packages"
        run: npm install
      - name: "Install backend packages and start server"
        run: |
          pushd ./invoice-rest-api
          npm install
          npm run build
          cp .env.example .env
          popd
      - name: "Start backend and frontend servers"
        run: |
          sed -i 's#../invoice-rest-api#./invoice-rest-api#g' docker-compose.yml
          docker-compose up -d
      - name: "Check server status"
        run: |
          sleep 5
          docker-compose ps
          netstat --tcp --listen
          curl -vvv -X GET \
            'http://127.0.0.1:3139/clients?params=%7B%22limit%22%3A5000%7D' \
            -H 'authorization: Bearer 111'
          exit 1
      - name: "Run cypress"
        run: npm run cypress:headless